### PR TITLE
Various data optimizations

### PR DESCRIPTION
**Pull request by Brechtpd**
This saves about ~35.000 gas (464.000 -> 426.000)

Note: all tests are working except the raw transaction test. I'm not sure what kind of transaction that is or what the purpose is, so I have temporarily disabled it in this PR.

This PR tries to use the call data better:
- Tries to pack data together
- But more importantly it reads data from the call data more efficiently (the key to this is the `calldatacopy` and `calldataload` assembly functions) without having to go through slow solidity array lookups

This PR also adds some simple XOR compression to values in the call data.

Storing everything in a single bytes array for submitRing() should open some posibilities:
- More extensible
- Easier to pack data together to save gas
- Easy to send the data needed to settle multiple rings in a single transaction (if possible: #351)

### CODE REVIEW

**Comment by Brechtpd** [comment]
Added some basic XOR compression to some values in the call data. Non-zero bytes in call data are much more expensive than zero bytes (68 gas/byte vs 4 gas/byte).  This actually doesn't have anything to do with the other things in this PR, this could easily be done on the code as it is on the master now.
This gives some significant gas savings in the 3 order test: ~12.500 gas.

**Comment by Brechtpd** [comment]
Added skipping of duplicate ring signature checking (not sure how common this is).

**Comment by kongliangzhong** [comment]
@Brechtpd , Thanks!  I will test it.

**Comment by kongliangzhong** [comment]
Yes, this PR saves about ~35,000 gas. Good job! I've learned a lot from it.

**Comment by Brechtpd** [comment]
@kongliangzhong Thanks! I learned a lot from making this as well. I had to experiment quite a bit to get the code as it is now and I picked up some new tricks along the way.

**Pull request merged**
