### PR TITLE
More general 'Optimized wallet address fetching' + misc optimizations

### PR DESCRIPTION
**Pull request by Brechtpd**
This is an alternative for PR #285. This solution does not depend on all wallet IDs to be the same, so I like this one better.

This saves about ~4000 gas (at least, that's what I'm measuring).

- I had to remove the 'p' and 'order' variables to make room on the stack for the new 'walletFeeRecipients' variable (arrays take 2 slots on the stack).
- getFeeRecipientByIdBatch fetches are done in batches of 3. Solidity doesn't support returning dynamic arrays so this is done as a workaround. The code for this is pretty clean and simple so this doesn't add much complexity.
- I still check in getFeeRecipientByIdBatch() if the wallet IDs are the same. I still feel like this might happen a lot, but this can be removed if needed.

### CODE REVIEW

**Comment by kongliangzhong** [comment]
It saves about 1500 gas as i tested.

**Comment by Brechtpd** [comment]
Added PR #288 and PR #294 to this pull request.

Gas savings should be ~6000 (470.000 -> 464.000) though I seem to be getting different results than kongliangzhong.

**Comment by Brechtpd** [comment]
No problem. Updated this pull request. NameRegistry has been removed so all optimizations with that went away. Now there's a gas saving of about ~2000 (455.000 -> 453.000)

**Comment by Brechtpd** [comment]
... and after the latest merge we're down to about ~1000 (452.500 -> 451.500).

**Comment by dong77** [comment]
Thank you, @Brechtpd. Glad to see you again.

@kongliangzhong will verify your finding and take care of this PR. 👍

**Comment by kongliangzhong** [comment]
It saved ~500 gas for a 2-orders-ring and ~1500 gas for a 3-orders-ring as i measured.

**Pull request merged**
