### PR TITLE
[Optimisation/Issue#135] Encoding based optimisations. [Fully Working Tests]

### PR DESCRIPTION
**Pull request by Hephyrius**
This optimisation works on the ideas Daniel proposed in #135.  The Key difference is that Encoding is done within a uint8 rather than a uint256.

Variables that have been updated are marginSplitPercentage and buyNoMoreB. Rather than having two completly different values, a uint8 and a bool over 2 byes, they are represented in a single byte via a uint8.  This saves a little gas.

By Extension, The buyNoMoreBList has been removed, with the uint8ArgsList taking on the values as an indirect result of the merged variables. This also reduces memory usage as n-bytes for any nth sized rings are now removed. Saving further gas.

The encoding schema is as follows. A uint8 represents 8 bits, with a maximum int value of 255. The encoding schema makes use of the fact that the percentage will never be above 100% and that the 8th bit represents a value of 128. In essense, the boolean value of true has been replaced with an addition of 128, with false having no addition. 

bitwise operations now check to see if a value is >127, as this would infer a true boolean value. All related functionality has been updated in this regard. 

A visual represenation of this change can be seen below:

image

I will be exploring ways of combining this methodology with ideas from #135  and #130 as further work.

### CODE REVIEW

**Comment by dong77** [comment]
Great. I'll need some time to review this work. Please be a little bit patient.

**Comment by dong77** [comment]
Without looking into the detail. What I wanted to do is to introduce more flag-type parameters for Order. Is it likely that uint8 is less extensible?

**Comment by Hephyrius** [comment]
The choice of uint8 was based on saving gas for the 31 - 0 value bytes that a uint258 would introduce.  In terms of future flags, I feel a uint8 approach may be better. If need be, 32 different uint8 flags could be  chained together to form a byte32.  

Take your time :) the changes aren't critical for the short term.  In terms of the gas, I'm just running the scripts in the /bounty/ folder, I'll post results shortly.

**Comment by Hephyrius** [comment]
I'm getting a varied rate of gas reduction between 2000 and 1000.

**Comment by dong77** [comment]
@Hephyrius  Could you please resolve #186 within this PR. By doing that, you can demonstrate this solution is extensible to a certain degree. Then lets merge this PR into master.

**Pull request closed without merging**
