### PR TITLE
WIP: Cancel order for specific trading pair

### PR DESCRIPTION
**Pull request by prakal**
Adds additional tests for `setTradingPairCutoff` and some more minor changes. It also contains JS implementation of Keccak_256 for another test that verifies SHA combination as expected.

TODO:
1. `should not fill orders which have a timestamp before the cutoff set by setTradingPairCutoff.` test is not working because I am still trying to figure out how to set the order timestamps on the individual orders in testing, which would enable me to write tests for cutoff business logic. Some help would be great, @dong77

### CODE REVIEW

**Comment by dong77** [comment]
please create pull request.

**Comment by prakal** [comment]
Not sure I understand, @dong77. This is the pull request that contains the changes.

**Comment by dong77** [comment]
I’m here for help. Come to talk to me anytime you want.

**Comment by prakal** [comment]
Thanks, its going to take me some time to get to the convention center, so remote help would be appreciated. I'll try to summarize what I am failing to understand:

I am having issues with attaching a timeStamp on a particular order while testing. I am trying to do this to make sure that the `setTradingPairCutoff` method works and cancels previous orders on the trading pairs as expected.

**Comment by dong77** [comment]
You don’t attach a timestamp to orders. Attach timestamp to trading pair ids.

**Pull request closed without merging**
