### PR TITLE
Revert to using the delegate instead of address

### PR DESCRIPTION
**Pull request by BenjaminPrice**
By passing the delegate around we're able to refactor enough that we can use it in assembleOrders.
By using it also in assembleOrders we cut down on the SLOAD calls to the address on each iteration of the for loop.
This shows a savings of 398619->397712 (=907) for me

### CODE REVIEW

**Comment by dong77** [comment]
Please kindly resolve conflicts.

**Comment by BenjaminPrice** [comment]
Sure. One moment.

**Comment by BenjaminPrice** [comment]
Merge conflicts resolved.

**Comment by BenjaminPrice** [comment]
I'll resolve the conflicts caused by #102 merging before this...

**Comment by BenjaminPrice** [comment]
Resolved, again.

**Pull request merged**
