### PR TITLE
added boilerplate code for multihash

### PR DESCRIPTION
**Pull request by dong77**

### CODE REVIEW

**Comment by dong77** [comment]
I also see similar code on Github, please help us improve the existing code. A PR will be more than welcomed.

**Comment by Brechtpd** [comment]
See #321

**Comment by Hephyrius** [comment]
I feel like encoding the data as a bytes array would be a bit clunky and would waste a bit too much memory as an overhead, I do have an idea in mind but I'm unsure if Daniel would like it.  

What I propose is:
bytes32[] similar to the BatchTransfer bytes32[]. The very first element of the bytes32[] would be made up of all the V (uint8) values. Each byte of the bytes32 would be mapped to each order in a manner similar to the bit mapping used in feeselection. 

Once Tests are working for 1.6 and this, I will test the idea out and see if it holds water.

**Comment by Brechtpd** [comment]
@Hephyrius If I'm interpreting the code correctly, the idea seems to be that the code would support multiple ways of signing without changing the API, hence an opaque array of bytes that contains an ID for the algorithm that should be used for the verification. This way any data can be send for the verification as is needed for the chosen algorithm. Using anything else than a simple byte array (or something equivalent) would limit the extensibility.

**Comment by Hephyrius** [comment]
This is where the suggestion of the bytes32 being used as the V values could be explored further, say having the first byte of the first bytes32 item be the algorithm selected followed by the non-32byte encoded data for that sig, I think a bytes array is way too expensive and wasteful for most use cases.

**Comment by dong77** [comment]
the1.6 branch is still in its very early stage. The general idea is to support 
https://github.com/multiformats/multihash a bytearray signature scheme that is self-descriptive.

**Comment by dong77** [comment]
I need to do more testing to compare different options. My understanding (may be wrong) is that ‘bytes’ is cheaper than ‘byte[]’ which is basically  ‘byte1[]’, and ‘byte[]’ in our case is more suitable than ‘byte32[]’ as some signature may be say 33 bytes so ‘byte[]’ is going to save 32 bytes for us.

**Comment by Brechtpd** [comment]
That's correct Daniel. From the [solidity documentation](http://solidity.readthedocs.io/en/v0.4.23/types.html?highlight=arbitrary-length%20raw%20byte):

> Variables of type bytes and string are special arrays. A bytes is similar to byte[], but it is packed tightly in calldata. string is equal to bytes but does not allow length or index access (for now).
> 
> So bytes should always be preferred over byte[] because it is cheaper.

**Pull request merged**
