### PR TITLE
Optimisation: Remove Order and shift functionality to OrderState struct

### PR DESCRIPTION
**Pull request by Hephyrius**
**Gas Reduction :** ~2000 _(This needs verification)_

**Tests:** Fully working without changes

**Related PRs:** #286 - This PR fully integrates the former PR as it makes logical sense when re-purposing OrderState. Therefore I have closed the previous PR for now as this is the better of the two optimisations. 

**Notes:**  This optimisation removes the  order struct from the contract entirely, opting to use the OrderState struct in its place. The aim is to reduce gas via optimisation of memory usage. 

Originally, the contract would use OrderState, which contained order, but then also create an instance of Order in memory. Doubling the use of memory for essentially the same variables for no real reason.

The optimisation simply moves the variables from order to OrderState. All functions that used order have been changed to use OrderState . 
Across the two structs, "lrcFee" was used as a variable name. This optimisation changes the names of  "lrcFee" variables that originally belonged in OrderState to "lrcFeeState". 

This optimisation has a lot of scope for improvement, and I will be exploring this further. I will also be seeing how it can interact with my other unpublished, semi-working optimisations, for further gas reductions. 

**Edit:** Order struct has been added back for a single use case - cancel order - this is because it will have small savings in gas in this instance.

### CODE REVIEW

**Comment by kongliangzhong** [comment]
I merged you prior PR and now this branch has conflicts. May you resolve it first?

**Comment by Hephyrius** [comment]
I think I have resolved the issue.

**Comment by kongliangzhong** [comment]
Please give me some time to test it.

**Comment by kongliangzhong** [comment]
I will merge other PRs first since this PR will has conflicts with them.

**Comment by Hephyrius** [comment]
No problems, I made changes to my personal code base earlier. I'll be committing an updated version shortly.

**Comment by Hephyrius** [comment]
I'm closing this request as the alternate version (#305) was merged

**Pull request closed without merging**
