### PR TITLE
Removed Ring struct to reduce memory use and copying of data

### PR DESCRIPTION
**Pull request by Brechtpd**
Most members were used rarely anyway.

### CODE REVIEW

**Comment by BenjaminPrice** [comment]
I had the exact same optimization get rejected. Daniel wants to keep the Ring struct.

https://github.com/Loopring/protocol/pull/64

**Comment by Brechtpd** [comment]
@BenjaminPrice Did you misread Ring for Rate? The pull request you referenced removed the Rate struct as far as I can see, I removed the Ring struct.

**Comment by BenjaminPrice** [comment]
Ah, you're right. Totally misread that.

**Comment by dong77** [comment]
I'm merging this to another branch to test it.

**Pull request merged**
